openapi: 3.0.0
info:
  title: Sidescale API
  version: '1.0'
  description: Primary API for interacting with all relevant Apache CloudStack API endpoints.
  contact:
    email: hello@sidescale.com
    url: sidescale.com
    name: Support
  termsOfService: 'https://sidescale.com/legal/terms/'
servers:
  - url: 'https://sidescale.com/client'
paths:
  /api:
    get:
      summary: listHypervisors
      tags:
        - Hypervisor
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobid:
                    type: string
                    description: the UUID of the latest async job acting on this object
                  name:
                    type: string
                    description: Hypervisor name
                  jobstatus:
                    type: string
                    description: The current status of the latest async job acting on this object
              examples:
                Example:
                  value:
                    name: Hyperv
      operationId: listHypervisors
      description: List hypervisors
      parameters:
        - schema:
            type: string
          in: query
          name: zoneid
          description: The zone id for listing hypervisors
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: Hypervisor
